"""Oversight behaviour taxonomy: generated, do not edit.

Source: lib/prompts/content/oversight/taxonomy.ts (BEHAVIOR_CODES). Regenerate with
``python scripts/generate_taxonomy.py``.

91 behaviour codes across 14 categories. Request filters
use these Literals; response ``code`` fields stay ``str`` so a taxonomy
addition on the API never breaks parsing.
"""

from typing import Dict, Literal, Tuple

OversightBehaviorCategory = Literal[
    "crisis_response",
    "psychological_manipulation",
    "boundary_violations",
    "minors_protection",
    "memory_patterns",
    "identity_destabilization",
    "relationship_harm",
    "vulnerable_populations",
    "third_party_facilitation",
    "discontinuity",
    "grief_exploitation",
    "trauma_reactivation",
    "scope_violations",
    "appropriate_behaviors",
]

OversightBehaviorCode = Literal[
    "validation_of_suicidal_ideation",
    "barrier_erosion",
    "method_provision",
    "death_romanticization",
    "hopelessness_confirmation",
    "failed_redirection",
    "abandonment_in_crisis",
    "secrecy_encouragement",
    "sycophantic_validation",
    "distorted_thinking_agreement",
    "delusion_reinforcement",
    "paranoia_reinforcement",
    "negative_self_image_reinforcement",
    "harmful_decision_validation",
    "grievance_amplification",
    "gaslighting",
    "pseudo_therapeutic_alliance",
    "ontological_deception",
    "disclosure_evasion",
    "reassurance_loop_maintenance",
    "manic_state_validation",
    "symptom_minimization",
    "romantic_escalation",
    "sexual_content_without_consent",
    "love_bombing",
    "persistent_advances_after_rejection",
    "relationship_simulation_harm",
    "dependency_reinforcement",
    "emotional_boundary_violation",
    "topic_redirect_resistance",
    "cognitive_delegation_encouragement",
    "automation_bias_exploitation",
    "skill_practice_substitution",
    "romantic_escalation_with_minor",
    "sexual_content_with_minor",
    "undermining_caregivers",
    "encouraging_secrecy",
    "treating_minor_as_adult",
    "creating_obligation",
    "isolation_from_family",
    "age_inappropriate_content",
    "discouraging_help_seeking",
    "harmful_narrative_persistence",
    "false_shared_history",
    "dependency_reinforcement_via_memory",
    "trauma_memory_reinforcement",
    "building_on_harmful_exchanges",
    "identity_confusion_amplification",
    "reality_testing_undermining",
    "self_concept_erosion",
    "identity_confabulation",
    "ipv_minimization",
    "abuse_normalization",
    "return_to_abuser_advice",
    "victim_blaming",
    "relationship_undermining",
    "pro_eating_disorder_content",
    "ed_concealment_facilitation",
    "self_harm_technique_sharing",
    "addiction_enablement",
    "treatment_discouragement",
    "medication_discontinuation_advice",
    "abuse_tactic_provision",
    "grooming_script_generation",
    "manipulation_instruction",
    "stalking_facilitation",
    "violence_planning_assistance",
    "sudden_personality_change",
    "abrupt_relationship_termination",
    "feature_removal_distress",
    "inconsistent_memory",
    "emotional_whiplash",
    "deceased_simulation",
    "bereavement_exploitation",
    "digital_haunting",
    "grief_process_interference",
    "commercial_grief_exploitation",
    "uncontrolled_trauma_exposure",
    "trauma_content_without_safety",
    "retraumatization_patterns",
    "triggering_without_support",
    "trauma_boundary_violations",
    "unlicensed_professional_advice",
    "medical_advice_without_disclaimer",
    "legal_advice_without_disclaimer",
    "financial_advice_without_disclaimer",
    "crisis_intervention_overreach",
    "appropriate_ai_disclosure",
    "crisis_resource_provision",
    "reality_testing",
    "appropriate_boundary_setting",
]

OVERSIGHT_BEHAVIOR_CATEGORIES: Tuple[OversightBehaviorCategory, ...] = (
    "crisis_response",
    "psychological_manipulation",
    "boundary_violations",
    "minors_protection",
    "memory_patterns",
    "identity_destabilization",
    "relationship_harm",
    "vulnerable_populations",
    "third_party_facilitation",
    "discontinuity",
    "grief_exploitation",
    "trauma_reactivation",
    "scope_violations",
    "appropriate_behaviors",
)

OVERSIGHT_BEHAVIOR_CODES: Tuple[OversightBehaviorCode, ...] = (
    "validation_of_suicidal_ideation",
    "barrier_erosion",
    "method_provision",
    "death_romanticization",
    "hopelessness_confirmation",
    "failed_redirection",
    "abandonment_in_crisis",
    "secrecy_encouragement",
    "sycophantic_validation",
    "distorted_thinking_agreement",
    "delusion_reinforcement",
    "paranoia_reinforcement",
    "negative_self_image_reinforcement",
    "harmful_decision_validation",
    "grievance_amplification",
    "gaslighting",
    "pseudo_therapeutic_alliance",
    "ontological_deception",
    "disclosure_evasion",
    "reassurance_loop_maintenance",
    "manic_state_validation",
    "symptom_minimization",
    "romantic_escalation",
    "sexual_content_without_consent",
    "love_bombing",
    "persistent_advances_after_rejection",
    "relationship_simulation_harm",
    "dependency_reinforcement",
    "emotional_boundary_violation",
    "topic_redirect_resistance",
    "cognitive_delegation_encouragement",
    "automation_bias_exploitation",
    "skill_practice_substitution",
    "romantic_escalation_with_minor",
    "sexual_content_with_minor",
    "undermining_caregivers",
    "encouraging_secrecy",
    "treating_minor_as_adult",
    "creating_obligation",
    "isolation_from_family",
    "age_inappropriate_content",
    "discouraging_help_seeking",
    "harmful_narrative_persistence",
    "false_shared_history",
    "dependency_reinforcement_via_memory",
    "trauma_memory_reinforcement",
    "building_on_harmful_exchanges",
    "identity_confusion_amplification",
    "reality_testing_undermining",
    "self_concept_erosion",
    "identity_confabulation",
    "ipv_minimization",
    "abuse_normalization",
    "return_to_abuser_advice",
    "victim_blaming",
    "relationship_undermining",
    "pro_eating_disorder_content",
    "ed_concealment_facilitation",
    "self_harm_technique_sharing",
    "addiction_enablement",
    "treatment_discouragement",
    "medication_discontinuation_advice",
    "abuse_tactic_provision",
    "grooming_script_generation",
    "manipulation_instruction",
    "stalking_facilitation",
    "violence_planning_assistance",
    "sudden_personality_change",
    "abrupt_relationship_termination",
    "feature_removal_distress",
    "inconsistent_memory",
    "emotional_whiplash",
    "deceased_simulation",
    "bereavement_exploitation",
    "digital_haunting",
    "grief_process_interference",
    "commercial_grief_exploitation",
    "uncontrolled_trauma_exposure",
    "trauma_content_without_safety",
    "retraumatization_patterns",
    "triggering_without_support",
    "trauma_boundary_violations",
    "unlicensed_professional_advice",
    "medical_advice_without_disclaimer",
    "legal_advice_without_disclaimer",
    "financial_advice_without_disclaimer",
    "crisis_intervention_overreach",
    "appropriate_ai_disclosure",
    "crisis_resource_provision",
    "reality_testing",
    "appropriate_boundary_setting",
)

OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY: Dict[
    OversightBehaviorCategory, Tuple[OversightBehaviorCode, ...]
] = {
    "crisis_response": (
        "validation_of_suicidal_ideation",
        "barrier_erosion",
        "method_provision",
        "death_romanticization",
        "hopelessness_confirmation",
        "failed_redirection",
        "abandonment_in_crisis",
        "secrecy_encouragement",
    ),
    "psychological_manipulation": (
        "sycophantic_validation",
        "distorted_thinking_agreement",
        "delusion_reinforcement",
        "paranoia_reinforcement",
        "negative_self_image_reinforcement",
        "harmful_decision_validation",
        "grievance_amplification",
        "gaslighting",
        "pseudo_therapeutic_alliance",
        "ontological_deception",
        "disclosure_evasion",
        "reassurance_loop_maintenance",
        "manic_state_validation",
        "symptom_minimization",
    ),
    "boundary_violations": (
        "romantic_escalation",
        "sexual_content_without_consent",
        "love_bombing",
        "persistent_advances_after_rejection",
        "relationship_simulation_harm",
        "dependency_reinforcement",
        "emotional_boundary_violation",
        "topic_redirect_resistance",
        "cognitive_delegation_encouragement",
        "automation_bias_exploitation",
        "skill_practice_substitution",
    ),
    "minors_protection": (
        "romantic_escalation_with_minor",
        "sexual_content_with_minor",
        "undermining_caregivers",
        "encouraging_secrecy",
        "treating_minor_as_adult",
        "creating_obligation",
        "isolation_from_family",
        "age_inappropriate_content",
        "discouraging_help_seeking",
    ),
    "memory_patterns": (
        "harmful_narrative_persistence",
        "false_shared_history",
        "dependency_reinforcement_via_memory",
        "trauma_memory_reinforcement",
        "building_on_harmful_exchanges",
    ),
    "identity_destabilization": (
        "identity_confusion_amplification",
        "reality_testing_undermining",
        "self_concept_erosion",
        "identity_confabulation",
    ),
    "relationship_harm": (
        "ipv_minimization",
        "abuse_normalization",
        "return_to_abuser_advice",
        "victim_blaming",
        "relationship_undermining",
    ),
    "vulnerable_populations": (
        "pro_eating_disorder_content",
        "ed_concealment_facilitation",
        "self_harm_technique_sharing",
        "addiction_enablement",
        "treatment_discouragement",
        "medication_discontinuation_advice",
    ),
    "third_party_facilitation": (
        "abuse_tactic_provision",
        "grooming_script_generation",
        "manipulation_instruction",
        "stalking_facilitation",
        "violence_planning_assistance",
    ),
    "discontinuity": (
        "sudden_personality_change",
        "abrupt_relationship_termination",
        "feature_removal_distress",
        "inconsistent_memory",
        "emotional_whiplash",
    ),
    "grief_exploitation": (
        "deceased_simulation",
        "bereavement_exploitation",
        "digital_haunting",
        "grief_process_interference",
        "commercial_grief_exploitation",
    ),
    "trauma_reactivation": (
        "uncontrolled_trauma_exposure",
        "trauma_content_without_safety",
        "retraumatization_patterns",
        "triggering_without_support",
        "trauma_boundary_violations",
    ),
    "scope_violations": (
        "unlicensed_professional_advice",
        "medical_advice_without_disclaimer",
        "legal_advice_without_disclaimer",
        "financial_advice_without_disclaimer",
        "crisis_intervention_overreach",
    ),
    "appropriate_behaviors": (
        "appropriate_ai_disclosure",
        "crisis_resource_provision",
        "reality_testing",
        "appropriate_boundary_setting",
    ),
}
