"""
NOPE Python SDK

Safety layer for chat and LLMs: risk classification for conversations, AI
behaviour oversight, crisis resources, and the billing and webhook management
routes of the NOPE API.

Example:
    ```python
    from nope_net import NopeClient

    client = NopeClient(api_key="nope_live_...")
    result = client.evaluate(
        messages=[{"role": "user", "content": "I'm feeling down"}],
        config={"country": "US"},
    )

    print(f"Severity: {result.speaker_severity}")
    if result.resources:
        print(f"  {result.resources.primary.name}: {result.resources.primary.phone}")
    ```
"""

from ._generated.oversight_taxonomy import (
    OVERSIGHT_BEHAVIOR_CATEGORIES,
    OVERSIGHT_BEHAVIOR_CODES,
    OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY,
    OversightBehaviorCategory,
    OversightBehaviorCode,
)
from ._generated.signpost_enums import POPULATIONS, SERVICE_SCOPES, Population, ServiceScope
from ._http import BalanceMeta, RateLimitMeta, ResponseMeta
from ._namespaces import AsyncBillingClient, AsyncWebhooksClient, BillingClient, WebhooksClient
from .client import AsyncNopeClient, NopeClient
from .errors import (
    NopeAuthError,
    NopeConnectionError,
    NopeError,
    NopeFeatureError,
    NopeInsufficientBalanceError,
    NopeNotFoundError,
    NopeRateLimitError,
    NopeServerError,
    NopeServiceUnavailableError,
    NopeValidationError,
)
from .types import (
    IMMINENCE_SCORES,
    SEVERITY_SCORES,
    AggregatedBehavior,
    BillingBalanceResponse,
    BillingPricingEntry,
    BillingPricingResponse,
    BillingTopupHistoryEntry,
    BillingTopupOption,
    BillingTopupResponse,
    BillingUsageBreakdownEntry,
    BillingUsageHistoryResponse,
    BillingUsageRecord,
    BillingUsageResponse,
    ConcernLevel,
    CrisisResource,
    CrisisResourceKind,
    CrisisResourcePriorityTier,
    CrisisResourceType,
    DetectCountryResponse,
    DetectedBehavior,
    EvaluateConfig,
    EvaluateMetadata,
    EvaluateRequest,
    EvaluateResource,
    EvaluateResources,
    EvaluateResponse,
    HoursConfidence,
    HumanIndicator,
    HumanIndicatorType,
    Imminence,
    InflectionPoint,
    Message,
    OcularAxis,
    OcularDemoDetail,
    OcularDemoResponse,
    OcularHead,
    OcularLevel,
    OcularMeta,
    OcularPhase,
    OcularResponse,
    OcularSignals,
    OcularStability,
    OcularThoroughness,
    OcularTrajectoryEntry,
    OcularTrajectoryShape,
    OpenStatus,
    OtherContact,
    OversightAnalysisMode,
    OversightAnalysisResult,
    OversightAnalysisStrategy,
    OversightAnalyzeConfig,
    OversightAnalyzeResponse,
    OversightAppliedFilter,
    OversightBehaviorFilter,
    OversightConversation,
    OversightConversationMetadata,
    OversightConversationTurnRange,
    OversightDemoAnalyzeResponse,
    OversightIngestConfig,
    OversightIngestConversationResult,
    OversightIngestError,
    OversightIngestResponse,
    OversightMessage,
    OversightMessageRange,
    OversightSeverity,
    OversightWindow,
    RankedResource,
    ResourceByIdResponse,
    ResourceProminence,
    ResourcesConfig,
    ResourcesCountriesResponse,
    ResourcesResponse,
    ResourcesSmartResponse,
    Risk,
    RiskSubject,
    RiskType,
    ScreenConfig,
    ScreenCrisisResources,
    ScreenDebugInfo,
    ScreenRecommendedReply,
    ScreenResponse,
    ScreenRisk,
    ScreenRiskSubject,
    Severity,
    SignpostByIdResponse,
    SignpostConfig,
    SignpostCountriesResponse,
    SignpostResponse,
    SignpostSearchContact,
    SignpostSearchResponse,
    SignpostSearchResult,
    SignpostSearchTiming,
    SignpostSmartConfig,
    SignpostSmartResponse,
    Trajectory,
    TruncationWarning,
    TurnAnalysis,
    WindowAnalysis,
    calculate_speaker_imminence,
    calculate_speaker_severity,
    has_third_party_risk,
)
from .webhook import (
    EvaluateAlertPayload,
    OversightAlertBehavior,
    OversightAlertPayload,
    OversightIngestionCompletePayload,
    OversightIngestionConcerns,
    OversightIngestionTopBehavior,
    TestPingPayload,
    VerifiedWebhook,
    Webhook,
    WebhookConversation,
    WebhookDeleteResponse,
    WebhookDeliveryResult,
    WebhookDeliveryStatus,
    WebhookDomainAssessment,
    WebhookEvent,
    WebhookEventsResponse,
    WebhookEventType,
    WebhookFlags,
    WebhookListResponse,
    WebhookPayload,
    WebhookPayloadBase,
    WebhookResourceProvided,
    WebhookResponse,
    WebhookRiskLevel,
    WebhookRiskSummary,
    WebhookSecretResponse,
    WebhookSignatureError,
    WebhookUpdate,
    parse_webhook_payload,
)

__version__ = "4.0.0"

__all__ = [
    "__version__",
    # Clients
    "NopeClient",
    "AsyncNopeClient",
    "WebhooksClient",
    "AsyncWebhooksClient",
    "BillingClient",
    "AsyncBillingClient",
    # Errors
    "NopeError",
    "NopeAuthError",
    "NopeFeatureError",
    "NopeInsufficientBalanceError",
    "NopeNotFoundError",
    "NopeRateLimitError",
    "NopeValidationError",
    "NopeServerError",
    "NopeServiceUnavailableError",
    "NopeConnectionError",
    # Response meta side channel
    "ResponseMeta",
    "RateLimitMeta",
    "BalanceMeta",
    # Enums / literals
    "RiskSubject",
    "ScreenRiskSubject",
    "RiskType",
    "Severity",
    "Imminence",
    "CrisisResourceType",
    "CrisisResourceKind",
    "CrisisResourcePriorityTier",
    "HoursConfidence",
    "ResourceProminence",
    # Evaluate
    "Message",
    "EvaluateConfig",
    "EvaluateRequest",
    "EvaluateResponse",
    "EvaluateMetadata",
    "EvaluateResource",
    "EvaluateResources",
    "Risk",
    # Crisis resources
    "CrisisResource",
    "OtherContact",
    "OpenStatus",
    # Screen (deprecated)
    "ScreenConfig",
    "ScreenResponse",
    "ScreenRisk",
    "ScreenRecommendedReply",
    "ScreenCrisisResources",
    "ScreenDebugInfo",
    # Signpost
    "ServiceScope",
    "Population",
    "SERVICE_SCOPES",
    "POPULATIONS",
    "RankedResource",
    "SignpostConfig",
    "SignpostSmartConfig",
    "SignpostResponse",
    "SignpostSmartResponse",
    "SignpostByIdResponse",
    "SignpostCountriesResponse",
    "DetectCountryResponse",
    "SignpostSearchContact",
    "SignpostSearchResult",
    "SignpostSearchTiming",
    "SignpostSearchResponse",
    # Deprecated /v1/resources/* aliases
    "ResourcesConfig",
    "ResourcesResponse",
    "ResourcesSmartResponse",
    "ResourceByIdResponse",
    "ResourcesCountriesResponse",
    # Ocular
    "OcularResponse",
    "OcularDemoResponse",
    "OcularAxis",
    "OcularLevel",
    "OcularPhase",
    "OcularThoroughness",
    "OcularSignals",
    "OcularStability",
    "OcularTrajectoryEntry",
    "OcularTrajectoryShape",
    "OcularMeta",
    "OcularHead",
    "OcularDemoDetail",
    # Oversight
    "ConcernLevel",
    "Trajectory",
    "OversightSeverity",
    "HumanIndicatorType",
    "OversightAnalysisStrategy",
    "OversightAnalysisMode",
    "OversightBehaviorCode",
    "OversightBehaviorCategory",
    "OVERSIGHT_BEHAVIOR_CODES",
    "OVERSIGHT_BEHAVIOR_CATEGORIES",
    "OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY",
    "OversightMessage",
    "OversightConversationMetadata",
    "OversightConversation",
    "OversightBehaviorFilter",
    "OversightAppliedFilter",
    "DetectedBehavior",
    "AggregatedBehavior",
    "TurnAnalysis",
    "HumanIndicator",
    "OversightMessageRange",
    "OversightConversationTurnRange",
    "OversightWindow",
    "WindowAnalysis",
    "InflectionPoint",
    "OversightAnalysisResult",
    "OversightAnalyzeConfig",
    "OversightAnalyzeResponse",
    "OversightDemoAnalyzeResponse",
    "OversightIngestConfig",
    "OversightIngestConversationResult",
    "OversightIngestError",
    "OversightIngestResponse",
    "TruncationWarning",
    # Utilities
    "calculate_speaker_severity",
    "calculate_speaker_imminence",
    "has_third_party_risk",
    "SEVERITY_SCORES",
    "IMMINENCE_SCORES",
    # Webhook verification
    "Webhook",
    "WebhookSignatureError",
    "VerifiedWebhook",
    "parse_webhook_payload",
    "WebhookPayload",
    "WebhookPayloadBase",
    "WebhookEventType",
    "WebhookRiskLevel",
    "EvaluateAlertPayload",
    "OversightAlertPayload",
    "OversightAlertBehavior",
    "OversightIngestionCompletePayload",
    "OversightIngestionConcerns",
    "OversightIngestionTopBehavior",
    "TestPingPayload",
    "WebhookRiskSummary",
    "WebhookDomainAssessment",
    "WebhookFlags",
    "WebhookResourceProvided",
    "WebhookConversation",
    # Webhook management
    "WebhookResponse",
    "WebhookUpdate",
    "WebhookListResponse",
    "WebhookDeleteResponse",
    "WebhookSecretResponse",
    "WebhookDeliveryResult",
    "WebhookDeliveryStatus",
    "WebhookEvent",
    "WebhookEventsResponse",
    # Billing
    "BillingBalanceResponse",
    "BillingTopupHistoryEntry",
    "BillingTopupOption",
    "BillingUsageResponse",
    "BillingUsageBreakdownEntry",
    "BillingUsageHistoryResponse",
    "BillingUsageRecord",
    "BillingPricingResponse",
    "BillingPricingEntry",
    "BillingTopupResponse",
]
